package interfaces.clientes;

import dat.ClientesDAT;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Cliente;
import util.ListaDoble;
import util.Nodo;

/**
 *
 */
public class ClientesListInternalFrame extends javax.swing.JInternalFrame {
    
    private DefaultTableModel clientesModelTable;
    private ClientesDAT clientesDAT;

    /**
     * Creates new form ClientesListInternalFrame
     */
    public ClientesListInternalFrame() {        
        initCustom();
        cargarClientes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nuevoClienteButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        darBajaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(684, 526));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        nuevoClienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        nuevoClienteButton.setToolTipText("Nuevo Cliente");
        nuevoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoClienteButtonActionPerformed(evt);
            }
        });

        actualizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/refresh.png"))); // NOI18N
        actualizarButton.setToolTipText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        editarButton.setToolTipText("Actualizar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        darBajaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trash.png"))); // NOI18N
        darBajaButton.setToolTipText("Actualizar");
        darBajaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darBajaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darBajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(nuevoClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(darBajaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientesTable.setModel(clientesModelTable);
        jScrollPane1.setViewportView(clientesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoClienteButtonActionPerformed
        ClientesDialog clientesDialog = new ClientesDialog(null, true);
        clientesDialog.setLocationRelativeTo(this);
        clientesDialog.setVisible(true);        
    }//GEN-LAST:event_nuevoClienteButtonActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        // TODO add your handling code here:
        cargarClientes();
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        if (clientesTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Cliente"); return;
        }
        Cliente cliente = clientesDAT.getCliente( clientesTable.getSelectedRow() );
        System.out.println("cliente a editar es " + cliente);
        ClientesDialog clientesDialog = new ClientesDialog(null, true);
        clientesDialog.setParametros(cliente, true, clientesTable.getSelectedRow());         
        clientesDialog.setLocationRelativeTo(this);
        clientesDialog.setVisible(true);               
    }//GEN-LAST:event_editarButtonActionPerformed

    private void darBajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darBajaButtonActionPerformed
        if (clientesTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Cliente"); return;
        }
        Cliente cliente = clientesDAT.getCliente( clientesTable.getSelectedRow() );
        int op =JOptionPane.showConfirmDialog(rootPane, "Desea realmente dar de baja a "+cliente.getNombre()+" "+cliente.getApellido());
        System.out.println("op: "+ op);
        if(op == 0){
            cliente.setEstado(false);
            if(clientesDAT.guardarCliente(cliente, clientesTable.getSelectedRow())){
                cargarClientes();
                JOptionPane.showMessageDialog(rootPane, "Cliente Dado de baja satisfactoriamente");
            }
        }
    }//GEN-LAST:event_darBajaButtonActionPerformed
   
    
    private void cargarClientes() {
        clientesModelTable.setRowCount(0);        
        ListaDoble clientes = clientesDAT.listarClientesListaDobles();       
        Nodo aux = clientes.getNodoInicio();                
        while(aux != null) {      
            Cliente c = aux.getCliente();
            clientesModelTable.addRow(new Object[]{c.getCedula(), c.getNombre(),
                c.getApellido(), c.getGenero(), c.getTelefono(), c.getDireccion(),
                c.getMembresia(), c.getEstado()});
            aux = aux.getSiguiente();
        }
    }
    
    //Retorna las columnas para la tabla
    private String[] getColumnas() {
        return new String[]{"Cedula", "Nombres", "Apellidos", "Genero",
            "Telefono", "Direccion", "Membresia?", "Activo"};
    }
    
    private void initCustom() {
        clientesDAT = new ClientesDAT();
        clientesModelTable = new DefaultTableModel(null, getColumnas());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JTable clientesTable;
    private javax.swing.JButton darBajaButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevoClienteButton;
    // End of variables declaration//GEN-END:variables
    
}
