/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.facturacion;

import dat.ClientesDAT;
import dat.EmpleadosDAT;
import dat.FacturasDAT;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import pojo.Cliente;
import pojo.Empleado;
import pojo.Factura;
import pojo.TipoLavado;

/**
 * 
 */
public class NuevaFacturaDialog extends javax.swing.JDialog {
    
    private EmpleadosDAT empleadosDat;
    private ClientesDAT clientesDat;
    private FacturasDAT facturasDat;
    
    private TipoLavado tipoLavado;
    private Empleado empleado ;
    private Cliente cliente;
    private Factura factura;
    
    private boolean calculo;

    /**
     * Creates new form NuevaFacturaDialog
     */
    public NuevaFacturaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        empleadosDat = new EmpleadosDAT();
        List<Empleado> empleados = empleadosDat.listarEmpleados();
        if (empleados != null) {
            empleados.forEach((e) -> {
                cbxEmpleados.addItem(e);
                /*empleadosModelTable.addRow(new Object[]{e.getCedula(), e.getNombre(),
                e.getApellido(), e.getGenero(), e.getTelefono(), e.getDireccion(), "0", "0", e.getEstado()
                });*/
            });
        }
        
        clientesDat = new ClientesDAT();
        List<Cliente> clientes = clientesDat.listarClientes();
        if (clientes != null) {
            clientes.forEach((c) -> {
                cbxClientes.addItem(c);
            });
        }
        
        //List<TipoLavado> tiposLavado = new ArrayList<>();
        //LocalTime now = LocalTime.now();
        cbxTipoLavado.addItem( new TipoLavado("001", "Lavado Express", "Lavado Expreso", new Double(5), LocalTime.of(0, 15) ));
        cbxTipoLavado.addItem( new TipoLavado("002", "Lavado SemiCompleto", "Lavado SemiCompleto", new Double(15), LocalTime.of(0, 30) ));
        cbxTipoLavado.addItem( new TipoLavado("003", "Lavado Completo", "Lavado Completo", new Double(20), LocalTime.of(2, 0) ));
        
        
        
        
        facturasDat = new FacturasDAT();
        factura = new Factura();
        
        factura.setFecha(  new Date() );
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        txtFecha.setText(dateFormat.format(factura.getFecha()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxEmpleados = new javax.swing.JComboBox<>();
        cbxClientes = new javax.swing.JComboBox<>();
        guardarButton = new javax.swing.JButton();
        cbxTipoLavado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHoraLlegada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoraEntrega = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Escoger Empleado:");

        jLabel2.setText("Escoger Cliente:");

        cbxEmpleados.setName(""); // NOI18N

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon.png"))); // NOI18N
        guardarButton.setToolTipText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo Lavado");

        jLabel4.setText("Num Factura");

        jLabel5.setText("Hora Llegada");

        txtHoraLlegada.setText("00:00");

        jLabel6.setText("Tiempo Estimado:");

        txtHoraEntrega.setEnabled(false);

        jLabel7.setText("Fecha");

        txtFecha.setEnabled(false);

        jLabel8.setText("Subtotal");

        txtSubtotal.setEnabled(false);

        jLabel9.setText("Descuento");

        txtDescuento.setText("0");
        txtDescuento.setEnabled(false);

        txtTotal.setEnabled(false);

        jLabel10.setText("Iva");

        txtIva.setEnabled(false);

        jLabel11.setText("Total");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbxClientes, 0, 350, Short.MAX_VALUE)
                                            .addComponent(cbxTipoLavado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(txtHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addComponent(btnCalcular))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(107, 107, 107)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarButton)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxTipoLavado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(txtHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(guardarButton)
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        if (clientesDat.listarClientes() == null ){
            JOptionPane.showMessageDialog(rootPane, "Debe crear un cliente"); return;
        }
        if (empleadosDat.listarEmpleados() == null ){
            JOptionPane.showMessageDialog(rootPane, "Debe crear un Empleado"); return;
        }
        
        if(cliente == null && empleado == null && tipoLavado == null){
            JOptionPane.showMessageDialog(rootPane, "Faltan algunos calculos"); return;
        }
        
        if(txtHoraLlegada.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe digitar una hora de llegada"); return;
        }
        
        try{
            factura.setNumeroFactura(Long.parseLong(txtNumFactura.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Digite numero de factura valido"); return;
        }
        
        empleado = (Empleado) cbxEmpleados.getSelectedItem();
        cliente = (Cliente ) cbxClientes.getSelectedItem();
        tipoLavado = (TipoLavado) cbxTipoLavado.getSelectedItem();
        
        
        
        factura.setEmpleadoAsignado(empleado);
        factura.setCliente(cliente);
        factura.setTipoLavado(tipoLavado);
        System.out.println("factur a guardar: "+factura);
        if(facturasDat.guardarFactura(factura)){   
            int numFacturasCliente = facturasDat.numFacturasPorCliente(cliente);
            System.out.println("numFacturasClientevvv "+numFacturasCliente+" ----- "+cliente.getMembresia());
            if (numFacturasCliente > 1 && !cliente.getMembresia()){
                cliente.setMembresia(true);
                System.out.println("Con mebresia ");
                clientesDat.guardarCliente(cliente, cbxClientes.getSelectedIndex());
            }
            this.dispose();
        }
        
        
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        if (clientesDat.listarClientes() == null ){
            JOptionPane.showMessageDialog(rootPane, "Debe crear un cliente"); return;
        }
        if (empleadosDat.listarEmpleados() == null ){
            JOptionPane.showMessageDialog(rootPane, "Debe crear un Empleado"); return;
        }
        
        
        try{
            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ISO_LOCAL_TIME;
            factura.setHoraLlegada( LocalTime.parse(txtHoraLlegada.getText(), dateTimeFormatter) );            
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(rootPane, "Digite una hora valida");
            return;
        }
        
        empleado = (Empleado) cbxEmpleados.getSelectedItem();
        cliente = (Cliente ) cbxClientes.getSelectedItem();
        tipoLavado = (TipoLavado) cbxTipoLavado.getSelectedItem();
        
        if (tipoLavado.getTiempoEstimado().getHour()>0) {
            factura.setHoraEntrega(factura.getHoraLlegada()
                    .plusHours(tipoLavado.getTiempoEstimado().getHour()));            
        } else {
            factura.setHoraEntrega(factura.getHoraLlegada()
                    .plusMinutes(tipoLavado.getTiempoEstimado().getMinute()));
        }
        
        //int tiempoEnrega = tipoLavado.getTiempoEstimado().getHour()> 0 ? tipoLavado.getTiempoEstimado().getHour() : tipoLavado.getTiempoEstimado().getMinute();
        //factura.setHoraEntrega(factura.getHoraLlegada().plusMinutes(  tiempoEnrega ));
        txtHoraEntrega.setText(""+factura.getHoraEntrega());
        
            //Subtotal
        factura.setSubtotal( tipoLavado.getPvp() );
        txtSubtotal.setText(""+factura.getSubtotal());
        
        //Descuento
        System.out.println("mebresia: "+cliente.getMembresia());
        if(cliente.getMembresia()){
            factura.setDescuento( ((tipoLavado.getPvp()*10)/100) );            
        }else
            factura.setDescuento(new Double(0));
        

        txtDescuento.setText(""+factura.getDescuento());
        
        //Iva
        factura.setIva(   (tipoLavado.getPvp()*12)/100   );
        txtIva.setText(""+factura.getIva());
        
        //Total
        factura.setTotal(  factura.getSubtotal()-factura.getDescuento()+factura.getIva()  );
        txtTotal.setText(""+factura.getTotal());
        //calculo = true;
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaFacturaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaFacturaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaFacturaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaFacturaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaFacturaDialog dialog = new NuevaFacturaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<Cliente> cbxClientes;
    private javax.swing.JComboBox<Empleado> cbxEmpleados;
    private javax.swing.JComboBox<TipoLavado> cbxTipoLavado;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHoraEntrega;
    private javax.swing.JTextField txtHoraLlegada;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
