package interfaces.empleados;


import dat.EmpleadosDAT;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import pojo.Empleado;

/**
 * 
 */
public class EmpleadosListInternalFrame extends javax.swing.JInternalFrame {
    
    private DefaultTableModel empleadosModelTable;
    private EmpleadosDAT empleadosDat;

    /** Creates new form EmpleadosListInternalFrame */
    public EmpleadosListInternalFrame() {
        initCustom();
        cargarEmpleados();
        initComponents();
        jTable1.setModel(empleadosModelTable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nuevoEmpleadoButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        darBajaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Empleados");
        setSize(new java.awt.Dimension(648, 526));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        nuevoEmpleadoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        nuevoEmpleadoButton.setToolTipText("Nuevo Cliente");
        nuevoEmpleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEmpleadoButtonActionPerformed(evt);
            }
        });

        actualizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/refresh.png"))); // NOI18N
        actualizarButton.setToolTipText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        editarButton.setToolTipText("Actualizar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        darBajaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trash.png"))); // NOI18N
        darBajaButton.setToolTipText("Actualizar");
        darBajaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darBajaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoEmpleadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darBajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(darBajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(nuevoEmpleadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres", "Apellidos", "Genero", "Telefono", "Direccion", "Salario", "Año Ingreso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoEmpleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEmpleadoButtonActionPerformed

        EmpleadosDialog empleadosDialog = new EmpleadosDialog(null, true);
        empleadosDialog.setLocationRelativeTo(this);
        empleadosDialog.setVisible(true);
    }//GEN-LAST:event_nuevoEmpleadoButtonActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        cargarEmpleados();        
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        if (jTable1.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Empleado"); return;
        }
        Empleado empleado = empleadosDat.getEmpleado( jTable1.getSelectedRow() );
        System.out.println("Empleado a editar es " + empleado);
        EmpleadosDialog empleadosDialog = new EmpleadosDialog(null, true);
        empleadosDialog.setParametros(empleado, true, jTable1.getSelectedRow());         
        empleadosDialog.setLocationRelativeTo(this);
        empleadosDialog.setVisible(true);  
    }//GEN-LAST:event_editarButtonActionPerformed

    private void darBajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darBajaButtonActionPerformed
        if (jTable1.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Empleado"); return;
        }
        Empleado empleado = empleadosDat.getEmpleado( jTable1.getSelectedRow() );
        int op =JOptionPane.showConfirmDialog(rootPane, "Desea realmente dar de baja a "+empleado.getNombre()+" "+empleado.getApellido());
        if(op == 0){
            empleado.setEstado(false);
            if(empleadosDat.guardarEmpleado(empleado, jTable1.getSelectedRow())){
                cargarEmpleados();
                JOptionPane.showMessageDialog(rootPane, "Empleado Dado de baja satisfactoriamente");
            }
        }
    }//GEN-LAST:event_darBajaButtonActionPerformed
    
    private void cargarEmpleados() {
        empleadosModelTable.setRowCount(0);
        List<Empleado> empleados = empleadosDat.listarEmpleados();
        if (empleados != null) {
            empleados.forEach((e) -> {
                System.out.println("e es "+e);
                empleadosModelTable.addRow(new Object[]{e.getCedula(), e.getNombre(),
                e.getApellido(), e.getGenero(), e.getTelefono(), e.getDireccion(), e.getSalario(), e.getAnioIngreso(), e.getEstado()
                });
            });
        }
    }
    
    //Retorna las columnas para la tabla
    private String[] getColumnas() {
        return new String[]{"Cedula", "Nombres", "Apellidos", "Genero",
            "Telefono", "Direccion", "Salario", "Año Ingreso", "Activo"};
    }
    
    private void initCustom() {
        empleadosDat = new EmpleadosDAT();
        empleadosModelTable = new DefaultTableModel(null, getColumnas());        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton darBajaButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nuevoEmpleadoButton;
    // End of variables declaration//GEN-END:variables

}
