package interfaces;

import interfaces.clientes.ClientesListInternalFrame;
import interfaces.empleados.EmpleadosListInternalFrame;
import interfaces.facturacion.FacturacionListInternalFrame;

/**
 * 
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        empleadosMenuItem = new javax.swing.JMenuItem();
        clientesMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        facturacionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lavadora de Autos");

        jMenu1.setText("Administracion");

        empleadosMenuItem.setText("Empleados");
        empleadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(empleadosMenuItem);

        clientesMenuItem.setText("Clientes");
        clientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(clientesMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        facturacionMenuItem.setText("Facturacion");
        facturacionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturacionMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(facturacionMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMenuItemActionPerformed
        // TODO add your handling code here:
        ClientesListInternalFrame clientesListInternalFrame = new ClientesListInternalFrame();
        jDesktopPane.add(clientesListInternalFrame);
        clientesListInternalFrame.setVisible(true);
//        ClientesInternalFrame clientesInternalFrame = new ClientesInternalFrame();
//        jDesktopPane.add(clientesInternalFrame);
//        clientesInternalFrame.setVisible(true);
    }//GEN-LAST:event_clientesMenuItemActionPerformed

    private void empleadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosMenuItemActionPerformed
        EmpleadosListInternalFrame empleadosListInternalFrame = new
         EmpleadosListInternalFrame();
        jDesktopPane.add(empleadosListInternalFrame);
        empleadosListInternalFrame.setVisible(true);
    }//GEN-LAST:event_empleadosMenuItemActionPerformed

    private void facturacionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturacionMenuItemActionPerformed
        FacturacionListInternalFrame facturacionListInternalFrame = 
                new FacturacionListInternalFrame();
        jDesktopPane.add(facturacionListInternalFrame);
        facturacionListInternalFrame.setVisible(true);
    }//GEN-LAST:event_facturacionMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrincipalForm principalForm = new PrincipalForm();
                principalForm.setVisible(true);
                principalForm.setSize(829, 583);
                principalForm.setLocationRelativeTo(null);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clientesMenuItem;
    private javax.swing.JMenuItem empleadosMenuItem;
    private javax.swing.JMenuItem facturacionMenuItem;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
